import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

// Initialize Geist Sans and Mono fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Determine the initial theme for server-side rendering
  // Assuming system theme defaults to 'dark' for consistency; adjust if needed
  const initialTheme = "dark"; // Can be dynamically set based on logic or cookies
  const initialThemeStyle = { colorScheme: "dark" };

  return (
    <html lang="en" className={initialTheme} style={initialThemeStyle}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning // Suppresses warnings for browser extension attributes like cz-shortcut-listen
      >
        {/* ThemeProvider manages light/dark mode with system preference */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
